export const tables = [
  {
    id: 1,
    type: 'defaultTable',
    header: 'Fleet Identifiers',
    url: 'fleet-identifiers',
    collection: 'fleetidentifiers',
    fields: [
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Registration',
        fieldKey: 'registration',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'MSN',
        fieldKey: 'msn',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Aircraft Name',
        fieldKey: 'aircraftName',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Remarks',
        fieldKey: 'remarks',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
    ],
  },
  {
    id: 2,
    type: 'defaultTable',
    header: 'Aircraft Constants',
    url: 'aircraft-constants',
    collection: 'aircraftconstants',
    fields: [
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Reference Station',
        fieldKey: 'referenceStation',
        fieldType: 'number',
        required: false,
        defaultValue: '',
      },
      {
        fieldName: 'K Constant',
        fieldKey: 'kConstant',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'C Constant',
        fieldKey: 'cConstant',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Length of MAC',
        fieldKey: 'lengthOfMAC',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'LEMAC',
        fieldKey: 'lemac',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
    ],
  },
  {
    id: 3,
    type: 'defaultTable',
    header: 'BW/BI',
    url: 'basic-weights',
    collection: 'basicweights',
    fields: [
      {
        fieldName: 'Registration',
        fieldKey: 'registration',
        fieldType: 'registrationSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'BW',
        fieldKey: 'weight',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'BI',
        fieldKey: 'basicIndex',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Balance Arm',
        fieldKey: 'basicBalanceArm',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Effective From',
        fieldKey: 'effFrom',
        fieldType: 'date',
        required: false,
        defaultValue: null,
      },
      {
        fieldName: 'Effective To',
        fieldKey: 'effTo',
        fieldType: 'date',
        required: false,
        defaultValue: null,
      },
    ],
  },
  {
    id: 4,
    type: 'crewSeatsTable',
    withMapping: true,
    header: 'Crew Seats',
    url: 'crew-seats',
    collection: 'crewseats',
    navGroup: 'Cabin Fittings',
    fields: [
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftConstantsSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Configuration Name',
        fieldKey: 'configurationName',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Grid',
        fieldKey: 'grid',
        fieldType: 'grid',
        required: 'true',
        defaultValue: '',
      },
    ],
  },
  {
    id: 5,
    type: 'cabinTable',
    withMapping: true,
    header: 'Passenger Seats',
    url: 'passenger-seats',
    collection: 'passengerseats',
    navGroup: 'Cabin Fittings',
    fields: [
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftConstantsSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Configuration Name',
        fieldKey: 'configurationName',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Grid',
        fieldKey: 'grid',
        fieldType: 'grid',
        required: 'true',
        defaultValue: '',
      },
    ],
  },
  {
    id: 6,
    type: 'potableWaterTable',
    withMapping: true,
    header: 'Potable Water Loc.',
    url: 'potable-water-locations',
    collection: 'potablewaterlocations',
    navGroup: 'Cabin Fittings',
    fields: [
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftConstantsSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Configuration Name',
        fieldKey: 'configurationName',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Grid',
        fieldKey: 'grid',
        fieldType: 'grid',
        required: 'true',
        defaultValue: '',
      },
    ],
  },
  {
    id: 7,
    type: 'galleysTable',
    withMapping: true,
    header: 'Galleys & Other Loc.',
    url: 'galleys-and-other-locations',
    collection: 'galleysandotherlocations',
    navGroup: 'Cabin Fittings',
    fields: [
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftConstantsSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Configuration Name',
        fieldKey: 'configurationName',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Grid',
        fieldKey: 'grid',
        fieldType: 'grid',
        required: 'true',
        defaultValue: '',
      },
    ],
  },
  {
    id: 8,
    type: 'collapsibleTable',
    withMapping: true,
    header: 'Maximum Weights',
    url: 'maximum-weights',
    collection: 'maximumweights',
    fields: [
      {
        fieldName: 'Set Name',
        fieldKey: 'setName',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftConstantsSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'MFW',
        fieldKey: 'mfw',
        fieldType: 'number',
        required: false,
        defaultValue: '',
      },
      {
        fieldName: 'MZFW',
        fieldKey: 'mzfw',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'MTOW',
        fieldKey: 'mtow',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'MTW',
        fieldKey: 'mtw',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'MLW',
        fieldKey: 'mlw',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Status',
        fieldKey: 'status',
        fieldType: 'string',
        required: true,
        defaultValue: null,
      },
    ],
  },
  {
    id: 9,
    type: 'fuelTanksTable',
    withMapping: true,
    header: 'Fuel Data',
    url: 'fuel-data',
    collection: 'fueldata',
    fields: [
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftConstantsSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Fuel Tanks Configuration Name',
        fieldKey: 'tankName',
        fieldType: 'string',
        required: true,
        defaultValue: '',
        placeholder: 'e.g. "ALL TANKS"',
      },
      {
        fieldName: 'Fuel Density Range (kg/l) from',
        fieldKey: 'FDRFrom',
        fieldType: 'number',
        required: true,
        defaultValue: '',
        range: { name: 'fdr', type: 'start' },
        maxLength: 5,
        placeholder: 0.75,
      },
      {
        fieldName: 'Fuel Density Range to (kg/l)',
        fieldKey: 'FDRTo',
        fieldType: 'number',
        required: true,
        defaultValue: '',
        range: { name: 'fdr', type: 'end' },
        maxLength: 5,
        placeholder: 0.85,
      },
      {
        fieldName: 'Values Calculated at (kg/l)',
        fieldKey: 'FDCalcAt',
        fieldType: 'number',
        required: true,
        defaultValue: '',
        maxLength: 5,
        placeholder: 0.8,
      },
      {
        fieldName: 'Grid',
        fieldKey: 'grid',
        fieldType: 'grid',
        required: 'true',
        defaultValue: '',
      },
    ],
  },
  {
    id: 10,
    type: 'collapsibleTable',
    withMapping: true,
    header: 'Pantry Weights',
    url: 'pantry-weights',
    collection: 'pantryweights',
    fields: [
      {
        fieldName: 'Set Name',
        fieldKey: 'setName',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftConstantsSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Weight',
        fieldKey: 'weight',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Index',
        fieldKey: 'index',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Balance Arm',
        fieldKey: 'balanceArm',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
    ],
  },
  {
    id: 11,
    type: 'cargoHoldsTable',
    withMapping: true,
    header: 'Cargo Holds',
    url: 'cargo-holds',
    collection: 'cargoholds',
    fields: [
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftConstantsSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Configuration Name',
        fieldKey: 'configurationName',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Grid',
        fieldKey: 'grid',
        fieldType: 'grid',
        required: 'true',
        defaultValue: '',
      },
    ],
  },
  {
    id: 12,
    type: 'cgLimitsTable',
    withMapping: true,
    header: 'CG Limits',
    url: 'cg-limits',
    collection: 'cglimits',
    fields: [
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftConstantsSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Limits Name',
        fieldKey: 'limitsName',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Grid Front',
        fieldKey: 'gridFwd',
        fieldType: 'grid',
        required: 'true',
        defaultValue: '',
      },
      {
        fieldName: 'Grid Front',
        fieldKey: 'gridAft',
        fieldType: 'grid',
        required: 'true',
        defaultValue: '',
      },
    ],
  },
  {
    id: 13,
    type: 'stabiliserTrimTable',
    withMapping: true,
    header: 'Stabiliser Trim',
    url: 'stabiliser-trim',
    collection: 'stabilisertrim',
    fields: [
      {
        fieldName: 'Aircraft Type',
        fieldKey: 'aircraftType',
        fieldType: 'aircraftConstantsSelect',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Flap Setting',
        fieldKey: 'flapSetting',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Thrust Rating',
        fieldKey: 'thrustRating',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Grid',
        fieldKey: 'grid',
        fieldType: 'grid',
        required: 'true',
        defaultValue: '',
      },
    ],
  },
  {
    id: 14,
    type: 'defaultTable',
    header: 'SWA',
    url: 'swa',
    collection: 'swa',
    fields: [
      {
        fieldName: 'SWA Name',
        fieldKey: 'swaName',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Description',
        fieldKey: 'description',
        fieldType: 'string',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Effective From',
        fieldKey: 'effFrom',
        fieldType: 'date',
        required: false,
        defaultValue: null,
      },
      {
        fieldName: 'Effective To',
        fieldKey: 'effTo',
        fieldType: 'date',
        required: false,
        defaultValue: null,
      },
      {
        fieldName: 'Weight',
        fieldKey: 'weight',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Index',
        fieldKey: 'index',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
      {
        fieldName: 'Balance Arm',
        fieldKey: 'balanceArm',
        fieldType: 'number',
        required: true,
        defaultValue: '',
      },
    ],
  },
];
